### PR TITLE
[RTM] Support German Umlauts

### PR DESCRIPTION
**Pull request by MarkejN**
Fixes https://github.com/MetaModels/filter_register/issues/10

### CODE REVIEW

**Comment by zonky2** [comment]
@MarkejN fix author validation
https://travis-ci.com/github/MetaModels/filter_register/jobs/501127959#L870-L871

**Comment by zonky2** [comment]
@discordier what do you think - in MM 2.2 it works without problems with umlauts

**Comment by discordier** [comment]
The change is correct non-the-less, as we should always correctly operate on multibyte chars

**Review by discordier — APPROVED** [review]

**Comment by discordier** [comment]
#fix the authoring problems and this is good to go.

**Pull request merged**
